// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNifM-6iF3vGf81FlL8Su7ySErQkueS8',
    appId: '1:325994046644:web:1ab08f87aba3988e0563e1',
    messagingSenderId: '325994046644',
    projectId: 'fleetops-f9245',
    authDomain: 'fleetops-f9245.firebaseapp.com',
    storageBucket: 'fleetops-f9245.firebasestorage.app',
    measurementId: 'G-N9RFFYRPMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_SpE63k-Vq6-ZXzLxmi09xyeEm-Fjpk',
    appId: '1:325994046644:android:03963b270a38a8990563e1',
    messagingSenderId: '325994046644',
    projectId: 'fleetops-f9245',
    storageBucket: 'fleetops-f9245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvrnJStgveVnCO_mAwHX_E3xwGGAeW34',
    appId: '1:325994046644:ios:e2deeffad44a431f0563e1',
    messagingSenderId: '325994046644',
    projectId: 'fleetops-f9245',
    storageBucket: 'fleetops-f9245.firebasestorage.app',
    iosBundleId: 'com.fleetops.fleetopsAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvrnJStgveVnCO_mAwHX_E3xwGGAeW34',
    appId: '1:325994046644:ios:e2deeffad44a431f0563e1',
    messagingSenderId: '325994046644',
    projectId: 'fleetops-f9245',
    storageBucket: 'fleetops-f9245.firebasestorage.app',
    iosBundleId: 'com.fleetops.fleetopsAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNifM-6iF3vGf81FlL8Su7ySErQkueS8',
    appId: '1:325994046644:web:37189e5773f1f62f0563e1',
    messagingSenderId: '325994046644',
    projectId: 'fleetops-f9245',
    authDomain: 'fleetops-f9245.firebaseapp.com',
    storageBucket: 'fleetops-f9245.firebasestorage.app',
    measurementId: 'G-E0G8DG49J6',
  );
}
